### PR TITLE
feat: add docker-compose setup

### PR DESCRIPTION
**Pull request by tedmarov**
Work in Progress

### CODE REVIEW

**Comment by mike-audi** [comment]
@tedmarov @timoguin

I went thru the compose config and updated/fixed config issues + issues with the wrangler dockerfile

+ I organized everything into a nice docker-compose folder instead of being spread out across the other project features. 

HOWEVER, it still does not work. There is a configuration issue with the wrangler/minio set up.

The wrangler js code needs to be modified to be compatible with the local minio setup (uses https and shares the bucket name with the host url currently)

**Comment by timoguin** [comment]
> @tedmarov @timoguin
> 
> I went thru the compose config and updated/fixed config issues + issues with the wrangler dockerfile
> 
> + I organized everything into a nice docker-compose folder instead of being spread out across the other project features. 
> 
> HOWEVER, it still does not work. There is a configuration issue with the wrangler/minio set up.
> 
> The wrangler js code needs to be modified to be compatible with the local minio setup (uses https and shares the bucket name with the host url currently) 

Thanks!

Let's make it just a `docker/` directory and place the `docker-compose.yml` in the repo root.

**Comment by tedmarov** [comment]
> > @tedmarov @timoguin
> > 
> > I went thru the compose config and updated/fixed config issues + issues with the wrangler dockerfile
> > 
> > + I organized everything into a nice docker-compose folder instead of being spread out across the other project features. 
> > 
> > HOWEVER, it still does not work. There is a configuration issue with the wrangler/minio set up.
> > 
> > The wrangler js code needs to be modified to be compatible with the local minio setup (uses https and shares the bucket name with the host url currently) 
> 
> Thanks!
> 
> Let's make it just a `docker/` directory and place the `docker-compose.yml` in the repo root.

Is that something I need to do in addition to getting it working?

**Comment by timoguin** [comment]
> The wrangler js code needs to be modified to be compatible with the local minio setup (uses https and shares the bucket name with the host url currently)

Can you expound on this part a bit?

The worker code wants to use HTTPS (but HTTPS is not setup in MinIO)? And what do you mean about it sharing the bucket name with the host URL?

**Comment by timoguin** [comment]
> > > @tedmarov @timoguin
> > > 
> > > I went thru the compose config and updated/fixed config issues + issues with the wrangler dockerfile
> > > 
> > > + I organized everything into a nice docker-compose folder instead of being spread out across the other project features. 
> > > 
> > > HOWEVER, it still does not work. There is a configuration issue with the wrangler/minio set up.
> > > 
> > > The wrangler js code needs to be modified to be compatible with the local minio setup (uses https and shares the bucket name with the host url currently) 
> > 
> > Thanks!
> > 
> > Let's make it just a `docker/` directory and place the `docker-compose.yml` in the repo root.
> 
> Is that something I need to do in addition to getting it working?

We can do it either before or after. I was thinking @mike-audi could, but either way is fine.

**Comment by timoguin** [comment]
Also, if we're going to add unique names to Dockerfiles then let's do `Dockerfile.<name>` instead of using a prefix. But I would prefer to use directories for that, so we can do things like `docker/auth/Dockerfile` or `docker/storage/Dockerfile`. Then we can use the contexts `docker/auth/` and `docker/storage/` in the `docker-compose.yml`.

Does that make sense?

**Comment by mike-audi** [comment]
@tedmarov 
I suggest we merge this in as-is, and then I'll open a new GH Issue for the wrangler updates, as that has nothing to do with docker-compose.

@timoguin 
I actually have a whole slew of naming conventions I want to adjust (outside the scope of this PR). I suggest we discuss this separately & asap.

**Pull request merged**
